"""initial migration

Revision ID: fd719440f86d
Revises: 221309cfdfc4
Create Date: 2017-04-25 21:37:29.997000

"""

# revision identifiers, used by Alembic.
revision = 'fd719440f86d'
down_revision = '221309cfdfc4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
